eureka:
  server:
    host: eureka-server
    port: 8090
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/crm_poc_catalog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
  kafka:
    bootstrap-servers: kafka:9092
