spec:
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: EUREKA_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-bootstrap
                  key: eureka-host
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9050
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9050
              scheme: HTTP
            initialDelaySeconds: 30
