server:
  port: 9040
spring:
  application:
    name: api-documentation

management:
  endpoint:
    routes:
      enabled: true
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    host: localhost
    port: 8090

swagger:
  config:
    refreshrate: 5000

---

spring:
  profiles: dev

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: docker

eureka:
  server:
    host: eureka-server
    port: 8090

---

spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: test

eureka:
  instance:
    prefer-ip-address: true
