spring:
  application:
    name: customer-service
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    dbcp2:
      test-while-idle: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
    initialization-mode: always
    tomcat:
      max-wait: 15000
      max-active: 50
      test-on-borrow: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    properties:
      connection.characterEncoding: utf-8
      connection.CharSet: utf-8
      connection.useUnicode: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9070
  servlet:
    session:
      cookie:
        http-only: true

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    host: localhost
    port: 8090

kafka:
  topic:
    log: system-log

management:
  endpoint:
    health:
      enabled: true
      show-details: always

---

spring:
  profiles: dev
  datasource:
    url: ${jdbc.customer.url:${jdbc.url:jdbc:mysql://localhost:3306/crm_poc_customer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}}
    username: ${jdbc.customer.username:${jdbc.username:root}}
    password: ${jdbc.customer.password:${jdbc.password:admin}}
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: docker
  datasource:
    url: ${jdbc.customer.url:${jdbc.url:jdbc:mysql://mysql:3306/crm_poc_customer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}}
    username: ${jdbc.customer.username:${jdbc.username:root}}
    password: ${jdbc.customer.password:${jdbc.password:admin}}
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  server:
    host: eureka-server
    port: 8090
  instance:
    prefer-ip-address: true

---

spring:
  profiles: prod
  datasource:
    url: ${jdbc.customer.url:${jdbc.url:jdbc:mysql://mysql:3306/crm_poc_customer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}}
    username: ${jdbc.customer.username:${jdbc.username:root}}
    password: ${jdbc.customer.password:${jdbc.password:admin}}
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: test
  datasource:
    url: ${jdbc.customer.url:${jdbc.url:jdbc:mysql://localhost:3306/crm_poc_customer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}}
    username: ${jdbc.customer.username:${jdbc.username:root}}
    password: ${jdbc.customer.password:${jdbc.password:admin}}
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true