spring:
  application:
    name: eureka-server
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8090
  servlet:
    session:
      cookie:
        http-only: true

eureka:
  instance:
    appname: eureka-server
    instance-id: ${spring.application.name}-${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoint:
    health:
      enabled: true
      show-details: always

kafka:
  topic:
    log: system-log

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: localhost:9092

---

spring:
  profiles: docker
  kafka:
    bootstrap-servers: localhost:9092

---

spring:
  profiles: prod
  kafka:
    bootstrap-servers: localhost:9092

---

spring:
  profiles: test
  kafka:
    bootstrap-servers: localhost:9092
