spring:
  application:
    name: uaa-server
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 7000
  servlet:
    session:
      cookie:
        http-only: true

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    host: localhost
    port: 8090

kafka:
  topic:
    log: system-log

management:
  endpoint:
    health:
      enabled: true
      show-details: always

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: docker
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  server:
    host: eureka-server
    port: 8090
  instance:
    prefer-ip-address: true

---

spring:
  profiles: prod
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: test
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true
