spec:
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 30
