spring:
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true

customer-service:
  url: http://localhost:9060/ws/customers.wsdl?wsdl

catalog-service:
  url: http://localhost:9060/catalog-service/ws/catalogs.wsdl?wsdl