spring:
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  instance:
    prefer-ip-address: true
  server:
    host: eureka-server
    port: 8090

customer-service:
  url: http://api-gateway:9060/customer-service/ws/customers.wsdl?wsdl

catalog-service:
  url: http://api-gateway:9060/catalog-service/ws/catalogs.wsdl?wsdl
