spring:
  application:
    name: logger-service
  kafka:
    consumer:
      group-id: logger-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
server:
  port: 9090
  servlet:
    session:
      cookie:
        http-only: true

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:8090/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    host: localhost
    port: 8090

kafka:
  topic:
    log: system-log

management:
  endpoint:
    health:
      enabled: true
      show-details: always