spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: crmpoc-logger-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true
