
package com.crmpoc.catalog;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.crmpoc.catalog.GetAllProductRequest;
import com.crmpoc.catalog.GetAllProductResponse;
import com.crmpoc.catalog.GetProductDetailsRequest;
import com.crmpoc.catalog.GetProductDetailsResponse;
import com.crmpoc.catalog.ObjectFactory;
import com.crmpoc.catalog.OrderFulfilmentRequest;
import com.crmpoc.catalog.OrderFulfilmentResponse;
import com.crmpoc.catalog.SaveProductRequest;
import com.crmpoc.catalog.UpdateProductRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "CatalogPort", targetNamespace = "http://www.crmpoc.com/customer")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatalogPort {


    /**
     *
     * @param orderFulfilmentRequest
     * @return
     *     returns com.crmpoc.catalog.OrderFulfilmentResponse
     */
    @WebMethod(operationName = "OrderFulfilment")
    @WebResult(name = "OrderFulfilmentResponse", targetNamespace = "http://www.crmpoc.com/catalog", partName = "OrderFulfilmentResponse")
    public OrderFulfilmentResponse orderFulfilment(
        @WebParam(name = "OrderFulfilmentRequest", targetNamespace = "http://www.crmpoc.com/catalog", partName = "OrderFulfilmentRequest")
        OrderFulfilmentRequest orderFulfilmentRequest);

    /**
     *
     * @param getAllProductRequest
     * @return
     *     returns com.crmpoc.catalog.GetAllProductResponse
     */
    @WebMethod(operationName = "GetAllProduct")
    @WebResult(name = "GetAllProductResponse", targetNamespace = "http://www.crmpoc.com/catalog", partName = "GetAllProductResponse")
    public GetAllProductResponse getAllProduct(
        @WebParam(name = "GetAllProductRequest", targetNamespace = "http://www.crmpoc.com/catalog", partName = "GetAllProductRequest")
        GetAllProductRequest getAllProductRequest);

    /**
     *
     * @param getProductDetailsRequest
     * @return
     *     returns com.crmpoc.catalog.GetProductDetailsResponse
     */
    @WebMethod(operationName = "GetProductDetails")
    @WebResult(name = "GetProductDetailsResponse", targetNamespace = "http://www.crmpoc.com/catalog", partName = "GetProductDetailsResponse")
    public GetProductDetailsResponse getProductDetails(
        @WebParam(name = "GetProductDetailsRequest", targetNamespace = "http://www.crmpoc.com/catalog", partName = "GetProductDetailsRequest")
        GetProductDetailsRequest getProductDetailsRequest);

    /**
     *
     * @param saveProductRequest
     */
    @WebMethod(operationName = "SaveProduct")
    @Oneway
    public void saveProduct(
        @WebParam(name = "SaveProductRequest", targetNamespace = "http://www.crmpoc.com/catalog", partName = "SaveProductRequest")
        SaveProductRequest saveProductRequest);

    /**
     *
     * @param updateProductRequest
     */
    @WebMethod(operationName = "UpdateProduct")
    @Oneway
    public void updateProduct(
        @WebParam(name = "UpdateProductRequest", targetNamespace = "http://www.crmpoc.com/catalog", partName = "UpdateProductRequest")
        UpdateProductRequest updateProductRequest);

}
