spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/

server:
  port: 9999

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    host: localhost
    port: 8090

management:
  endpoint:
    health:
      enabled: true
      show-details: always

---

spring:
  profiles: dev

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: prod

eureka:
  instance:
    prefer-ip-address: true

---

spring:
  profiles: test

eureka:
  instance:
    prefer-ip-address: true