spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: crmpoc-asset-service
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  server:
    host: eureka-server
    port: 8090
  instance:
    prefer-ip-address: true
